### ISSUE TITLE
async nbd interface as a separate crate?

### ISSUE THREAD

**Issue by joshtriplett** [oll3/ihop#1]
Would you consider making the async interface to NBD available as a separate crate?

You don't need to implement write or any of the other operations that aren't already implemented; I'd be happy to just have an interface that supports exposing an NBD socket that supports reads, and a second interface for taking an NBD socket and feeding it into the kernel.

**Comment by oll3** [comment]
Was kind of planning on it, just a bit lazy. Anyway here's a first [release](https://crates.io/crates/nbd-async). Probably full of bugs and missing stuff. But PR's are [welcomed](https://github.com/oll3/nbd-async)!

**Comment by joshtriplett** [comment]
Thank you very much, I appreciate it! This will help a great deal.

I posted [one request](https://github.com/oll3/nbd-async/issues/1) to the new project, regarding separating the code for responding to NBD requests from the code for attaching an NBD device. Other than that, this is *exactly* what I need.

**Comment by joshtriplett** [comment]
Closing this issue as done.
